node('zh-jnlp') {
    stage('Prepare') {
            echo "1.Prepare Stage"
            checkout scm
            script {
                APP_NAME='auth'
                APP_ENV='test'
                DEPLOY_ENV='测试环境'
                // 应用tag
                APP_TAG="${env.APP_ENV}-${env.GIT_COMMIT}"
                // Git提交ID
                GIT_COMMIT=sh(returnStdout: true, script: 'git describe --tags --always').trim()
            }
        }
      stage('Clone') {
            echo "1.Clone Stage"
            git url: "https://github.com/phpzhou112/auth.git"
        }

        stage('Build Docker') {
            sh "docker build -t 1123/jenkins-demo:${APP_TAG} --build-arg APPNAME=${APP_NAME} -f deploy/${APP_ENV}/Dockerfile ."
        }
        stage('Push Docker') {
            echo "3.Push Docker Image Stage"
            withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                sh "docker login -u ${dockerHubUser} -p ${dockerHubPassword}"
                sh "docker push 1123/jenkins-demo:${APP_TAG}"
            }
        }
        stage('Deploy') {
            echo "4. Deploy Stage"
            sh "sed -i 's/<BUILD_TAG>/${APP_TAG}/' deploy/${APP_ENV}/k8s.yaml"
            sh "sed -i 's/<APP_NAME>/${APP_NAME}/' deploy/${APP_ENV}/k8s.yaml"
            sh "kubectl apply -f deploy/${APP_ENV}/k8s.yaml --record"
        }
}